#!/usr/bin/env bash
#csript to configure domain zone so that the subdomain www points to
#lb-01, lb-01 to lb-01 IP; web-01 to web-01 IP and web-02 to web-02 IP

print_domain_subdomain () {
	dig "$1" | grep -A1 'ANSWER SECTION:' | sed -r "s/$1./$2/g" | awk -F" " ' NR==2 { print "The subdomain " $1 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 2 ]
then
	print_domain_subdomain "$2.$1" "$2"
else
	print_domain_subdomain "www.$1" "www"
	print_domain_subdomain "lb-01.$1" "lb-01"
	print_domain_subdomain "web-01.$1" "web-01"
	print_domain_subdomain "web-02.$1" "web-02"
fi
