#!/usr/bin/env bash
# script to display Best School then hi at the 9th time but has 10 iterations using while

counter=0

while [ $counter -le 10 ]
do
	if [ $counter -eq 9 ]
	then 
		echo "Hi"
	else
		echo "Best School"
	fi
	((counter ++))
done
