#!/usr/bin/env bash
# script to display Best School then hi at the 9th time but has 10 iterations using while

counter=0

while [ $counter -lt 10 ]
do
	if [ $counter -eq 4 ]
	then 
		echo "bad luck"
	elif [ $counter -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter ++))
done
