#!/usr/bin/env bash
# script to display numbers 1-20 and displays
# 4 and bad luck from China 
# displays 9 and then bad luck from Japan for the 9th loop iteration
# and 17 and then bad luck from Italy for the 17th loop iteration

counter=1

while [ $counter -le 20 ]
do
	echo $counter
	case $counter in 
		4)
			echo "bad luck from China"
			;;
		9)
			echo  "bad luck from Japan"
			;;
		17)
			echo  "bad luck from Italy"
			;;
	esac
	((counter ++))
done
